/*
  +----------------------------------------------------------------------+
  | PHP Version 5                                                        |
  +----------------------------------------------------------------------+
  | Copyright (c) 1997-2014 The PHP Group                                |
  +----------------------------------------------------------------------+
  | This source file is subject to version 3.01 of the PHP license,      |
  | that is bundled with this package in the file LICENSE, and is        |
  | available through the world-wide-web at the following url:           |
  | http://www.php.net/license/3_01.txt                                  |
  | If you did not receive a copy of the PHP license and are unable to   |
  | obtain it through the world-wide-web, please send a note to          |
  | license@php.net so we can mail you a copy immediately.               |
  +----------------------------------------------------------------------+
  | Author:                                                              |
  +----------------------------------------------------------------------+
*/

/* $Id$ */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "php_ini.h"
#include "ext/standard/info.h"
#include "php_wechat.h"
#include "udp_parse.h"
#include "udp_type.h"
#include "tea.h"

#ifndef PHP_FE_END
#define PHP_FE_END {NULL, NULL, NULL}
#endif

ZEND_BEGIN_ARG_INFO_EX(arginfo_wechat_unpack, 0, 0, 3)
	ZEND_ARG_INFO(0, $buff)
	ZEND_ARG_INFO(0, $format)
	ZEND_ARG_INFO(1, $out)
ZEND_END_ARG_INFO()


/* True global resources - no need for thread safety here */
static int le_wechat;

/* {{{ wechat_functions[]
 *
 * Every user visible function must have an entry in wechat_functions[].
 */
const zend_function_entry wechat_functions[] = {
    PHP_FE(confirm_wechat_compiled, NULL)   /* For testing, remove later. */
    PHP_FE(wechat_udp_set_global, NULL)
    PHP_FE(wechat_udp_version, NULL)
    PHP_FE(wechat_udp_bind_pack, NULL)
    PHP_FE(wechat_udp_bind_unpack, NULL)
    PHP_FE(wechat_udp_control_pack, NULL)
    PHP_FE(wechat_udp_control_unpack, NULL)
    PHP_FE(wechat_udp_hex_unpack, NULL)
    PHP_FE(wechat_pack, NULL)
    PHP_FE(wechat_unpack, arginfo_wechat_unpack)

    PHP_FE(wechat_udp_control_devinfo_unpack, NULL)
    PHP_FE(mycrypt_xxtea, NULL)
    PHP_FE_END	/* Must be the last line in wechat_functions[] */
};
/* }}} */

/* {{{ wechat_module_entry
 */
zend_module_entry wechat_module_entry = {
#if ZEND_MODULE_API_NO >= 20010901
    STANDARD_MODULE_HEADER,
#endif
    "wechat",
    wechat_functions,
    PHP_MINIT(wechat),
    PHP_MSHUTDOWN(wechat),
    PHP_RINIT(wechat),  /* Replace with NULL if there's nothing to do at request start */
    PHP_RSHUTDOWN(wechat),  /* Replace with NULL if there's nothing to do at request end */
    PHP_MINFO(wechat),
#if ZEND_MODULE_API_NO >= 20010901
    PHP_WECHAT_VERSION,
#endif
    STANDARD_MODULE_PROPERTIES
};
/* }}} */

#ifdef COMPILE_DL_WECHAT
ZEND_GET_MODULE(wechat)
#endif

/* {{{ PHP_INI
 */
/* Remove comments and fill if you need to have entries in php.ini
PHP_INI_BEGIN()
    STD_PHP_INI_ENTRY("wechat.global_value",      "42", PHP_INI_ALL, OnUpdateLong, global_value, zend_wechat_globals, wechat_globals)
    STD_PHP_INI_ENTRY("wechat.global_string", "foobar", PHP_INI_ALL, OnUpdateString, global_string, zend_wechat_globals, wechat_globals)
PHP_INI_END()
*/
/* }}} */


static void php_wechat_init_globals(zend_wechat_globals *wechat_globals)
{
    wechat_globals->debug_flag = 1;
}


/* {{{ PHP_MINIT_FUNCTION
 */
PHP_MINIT_FUNCTION(wechat)
{
/* If you have INI entries, uncomment these lines 
REGISTER_INI_ENTRIES();
*/
    REGISTER_LONG_CONSTANT("UC_GLOBAL_DEBUG",  UC_GLOBAL_DEBUG, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_REQUEST", UC_REQUEST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_ANSWER", UC_ANSWER, CONST_CS | CONST_PERSISTENT);    
    REGISTER_STRING_CONSTANT("UC_DATA",  UC_DATA, CONST_CS | CONST_PERSISTENT);
    REGISTER_STRING_CONSTANT("UC_RETURN_CODE",  UC_RETURN_CODE, CONST_CS | CONST_PERSISTENT);
    REGISTER_STRING_CONSTANT("UC_HEX_CODE",  UC_HEX_CODE, CONST_CS | CONST_PERSISTENT);

    REGISTER_LONG_CONSTANT("UCOT_GET_ALL_ATTRI", UCOT_GET_ALL_ATTRI, CONST_CS | CONST_PERSISTENT);
    /*****************************************
    UDP Control Object Type
    UDP Control Sub Object Type
    UDP Control Attribute Type
    ****************************************/
    /*
    system. (系统)
    */
    REGISTER_LONG_CONSTANT("UCOT_SYSTEM", UCOT_SYSTEM, CONST_CS | CONST_PERSISTENT);
    
    // system.support.
    REGISTER_LONG_CONSTANT("UCSOT_SYS_SUPPORT", UCSOT_SYS_SUPPORT, CONST_CS | CONST_PERSISTENT);
    // system.support.support
    REGISTER_LONG_CONSTANT("UCAT_SUPPORT_SUPPORT", UCAT_SUPPORT_SUPPORT, CONST_CS | CONST_PERSISTENT);
    
    // system.hostname.
    REGISTER_LONG_CONSTANT("UCSOT_SYS_HOSTNAME", UCSOT_SYS_HOSTNAME, CONST_CS | CONST_PERSISTENT);
    // system.hostname.hostname
    REGISTER_LONG_CONSTANT("UCAT_HOSTNAME_HOSTNAME", UCAT_HOSTNAME_HOSTNAME, CONST_CS | CONST_PERSISTENT);
    
    // system.software.
    REGISTER_LONG_CONSTANT("UCSOT_SYS_SOFTWARE", UCSOT_SYS_SOFTWARE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_REBOOT", UCAT_SYS_REBOOT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_UPTIME", UCAT_SYS_UPTIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_IP", UCAT_SYS_IP, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_SVN", UCAT_SYS_SVN, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_SSID", UCAT_SYS_SSID, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_PASSWD", UCAT_SYS_PASSWD, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_DEVSTATUS", UCAT_SYS_DEVSTATUS, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_COM_DATE", UCAT_SYS_COM_DATE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_COM_TIME", UCAT_SYS_COM_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_SYSTIME", UCAT_SYS_SYSTIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_SET_SYSTIME", UCAT_SYS_SET_SYSTIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_DEBUGINFO", UCAT_SYS_DEBUGINFO, CONST_CS | CONST_PERSISTENT);
    // system.software.version
    REGISTER_LONG_CONSTANT("UCAT_SYS_VERSION", UCAT_SYS_VERSION, CONST_CS | CONST_PERSISTENT);
    // system.software.upgrade
    REGISTER_LONG_CONSTANT("UCAT_SYS_UPGRADE", UCAT_SYS_UPGRADE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SYS_STM_UPGRADE", UCAT_SYS_STM_UPGRADE, CONST_CS | CONST_PERSISTENT);
    
    
    // system.upgrade.
    REGISTER_LONG_CONSTANT("UCSOT_SYS_UPGRADE", UCSOT_SYS_UPGRADE, CONST_CS | CONST_PERSISTENT);
    
    // system.hardware.
    REGISTER_LONG_CONSTANT("UCSOT_SYS_HARDWARE", UCSOT_SYS_HARDWARE, CONST_CS | CONST_PERSISTENT);
    // system.hardware.LED
    REGISTER_LONG_CONSTANT("UCAT_HARDWARE_LED", UCAT_HARDWARE_LED, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_HARDWARE_LEDCOLOR", UCAT_HARDWARE_LEDCOLOR, CONST_CS | CONST_PERSISTENT);
    
    // system.vendor.
    REGISTER_LONG_CONSTANT("UCSOT_SYS_VENDOR", UCSOT_SYS_VENDOR, CONST_CS | CONST_PERSISTENT);
    // system.vendor.oem_id
    REGISTER_LONG_CONSTANT("UCAT_VENDOR_OEM_ID", UCAT_VENDOR_OEM_ID, CONST_CS | CONST_PERSISTENT);
    
    // system.server.
    REGISTER_LONG_CONSTANT("UCSOT_SYS_SERVER", UCSOT_SYS_SERVER, CONST_CS | CONST_PERSISTENT);
    // system.server.connect_time
    REGISTER_LONG_CONSTANT("UCAT_SERVER_CONNECT_TIME", UCAT_SERVER_CONNECT_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SERVER_DONAME", UCAT_SERVER_DONAME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_SERVER_IP", UCAT_SERVER_IP, CONST_CS | CONST_PERSISTENT);

    // system.user
    REGISTER_LONG_CONSTANT("UCSOT_SYS_USER", UCSOT_SYS_USER, CONST_CS | CONST_PERSISTENT);
    // system.user.passwd
    REGISTER_LONG_CONSTANT("UCAT_USER_PASSWD", UCAT_USER_PASSWD, CONST_CS | CONST_PERSISTENT);
    // system.user.location
    REGISTER_LONG_CONSTANT("UCAT_USER_LOCATION", UCAT_USER_LOCATION, CONST_CS | CONST_PERSISTENT);
    
    
    /*
    IA(智能电器)
    */
    // IA.
    REGISTER_LONG_CONSTANT("UCOT_IA", UCOT_IA, CONST_CS | CONST_PERSISTENT);

	// RF网关
	REGISTER_LONG_CONSTANT("UCSOT_IA_RFGW", UCSOT_IA_RFGW, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_JOIN", UCAT_IA_RFGW_JOIN, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_JOIN_FIND", UCAT_IA_RFGW_JOIN_FIND, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_JOIN_ACTION", UCAT_IA_RFGW_JOIN_ACTION, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_GROUP", UCAT_IA_RFGW_GROUP, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_LIST", UCAT_IA_RFGW_LIST, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_TT", UCAT_IA_RFGW_TT, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_DEV_SYNC", UCAT_IA_RFGW_DEV_SYNC, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_PARAM", UCAT_IA_RFGW_PARAM, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_TT_CACHE", UCAT_IA_RFGW_TT_CACHE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_LIST_DIGEST", UCAT_IA_RFGW_LIST_DIGEST, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_LIST_DIGEST_ACK", UCAT_IA_RFGW_LIST_DIGEST_ACK, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_IA_RFGW_LIST_WITH_ID", UCAT_IA_RFGW_LIST_WITH_ID, CONST_CS | CONST_PERSISTENT);

	//RF网关tlv
	REGISTER_LONG_CONSTANT("SMTDLOCK_CMD_GET_SUMMARY", SMTDLOCK_CMD_GET_SUMMARY, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SMTDLOCK_CMD_PUSH_SUMMARY", SMTDLOCK_CMD_PUSH_SUMMARY, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SMTDLOCK_CMD_GET_ONOFFTIME", SMTDLOCK_CMD_GET_ONOFFTIME, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SMTDLOCK_CMD_PUSH_ONOFFTIME", SMTDLOCK_CMD_PUSH_ONOFFTIME, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SMTDLOCK_CMD_SET_DEFENSE", SMTDLOCK_CMD_SET_DEFENSE, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("SMTDLOCK_CMD_SET_AUTO_DEFENSE", SMTDLOCK_CMD_SET_AUTO_DEFENSE, CONST_CS | CONST_PERSISTENT);
    
    // IA.stat
    REGISTER_LONG_CONSTANT("UCSOT_IA_STAT", UCSOT_IA_STAT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_TOTAL_PEAK", UCAT_STAT_TOTAL_PEAK, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_TOTAL_VALLEY", UCAT_STAT_TOTAL_VALLEY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_PERIOD_TIME", UCAT_STAT_PERIOD_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_PERIOD_PEAK", UCAT_STAT_PERIOD_PEAK, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_PERIOD_VALLEY", UCAT_STAT_PERIOD_VALLEY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_MONTH_PEAK", UCAT_STAT_MONTH_PEAK, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_MONTH_VALLEY", UCAT_STAT_MONTH_VALLEY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_CUR_POWER", UCAT_STAT_CUR_POWER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_PEAK_TIME", UCAT_STAT_PEAK_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_PEAK_PRICE", UCAT_STAT_PEAK_PRICE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_VALLEY_PRICE", UCAT_STAT_VALLEY_PRICE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_MONTH_FLAT", UCAT_STAT_MONTH_FLAT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_FLAT_TIME", UCAT_STAT_FLAT_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_FLAT_PRICE", UCAT_STAT_FLAT_PRICE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_VALLEY_TIME", UCAT_STAT_VALLEY_TIME, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_TOTAL_ELE", UCAT_STAT_TOTAL_ELE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_PHASE_ELE", UCAT_STAT_PHASE_ELE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_ON_ELE", UCAT_STAT_ON_ELE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_PUSH2SERV", UCAT_STAT_PUSH2SERV, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_ELE_DAYBYDAY", UCAT_STAT_ELE_DAYBYDAY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_CURR_POWER_MW", UCAT_STAT_CURR_POWER_MW, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_STAT_MAX", UCAT_STAT_MAX, CONST_CS | CONST_PERSISTENT);
    
    
    //商业悟空状态上报
    REGISTER_LONG_CONSTANT("UCT_STATE_ORI_ELE", UCT_STATE_ORI_ELE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_PUSH_TIMER_FAST", UCT_STATE_PUSH_TIMER_FAST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_PUSH_TIMER_HISTORY", UCT_STATE_PUSH_TIMER_HISTORY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_PUSH_AC_RUN", UCT_STATE_PUSH_AC_RUN, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_PUSH_POWER_ONEDAY", UCT_STATE_PUSH_POWER_ONEDAY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_PUSH_AC_ALARM", UCT_STATE_PUSH_AC_ALARM, CONST_CS | CONST_PERSISTENT);
    //统一配置下发
    REGISTER_LONG_CONSTANT("UCT_STATE_SET_PERSON_INDUCTION", UCT_STATE_SET_PERSON_INDUCTION, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_SET_AUTO_AJUST_TEMP", UCT_STATE_SET_AUTO_AJUST_TEMP, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_SET_ACOPEN_CURRENT_CHECK", UCT_STATE_SET_ACOPEN_CURRENT_CHECK, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_SET_AC_CURRENT_DEFALUT", UCT_STATE_SET_AC_CURRENT_DEFALUT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCT_STATE_SET_ACTEMP_RANGE", UCT_STATE_SET_ACTEMP_RANGE, CONST_CS | CONST_PERSISTENT);

    
    // IA.AIRCONDITION.
    REGISTER_LONG_CONSTANT("UCSOT_IA_AC", UCSOT_IA_AC, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_WORK", UCAT_AC_WORK, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_CUR_TEMP", UCAT_AC_CUR_TEMP, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_TIMER", UCAT_AC_TIMER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_SMART_ON", UCAT_AC_SMART_ON, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_SMART_OFF", UCAT_AC_SMART_OFF, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_SMART_SLEEP", UCAT_AC_SMART_SLEEP, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_SOUND_MATCH_REQUEST", UCAT_AC_SOUND_MATCH_REQUEST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_SOUND_DATA", UCAT_AC_SOUND_DATA, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_SOUND_MATCH_RESULT", UCAT_AC_SOUND_MATCH_RESULT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_ATTRI", UCAT_AC_ATTRI, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_MATCH_INFO", UCAT_AC_MATCH_INFO, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_AUTO_CTRL", UCAT_AC_AUTO_CTRL, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_ON_USER_SET", UCAT_AC_ON_USER_SET, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_CUR_RH", UCAT_AC_CUR_RH, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_TMP_SAMPLE_CURVE", UCAT_AC_TMP_SAMPLE_CURVE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_RH_SAMPLE_CURVE", UCAT_AC_RH_SAMPLE_CURVE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_LOCK", UCAT_AC_LOCK, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_AC_MAX", UCAT_AC_MAX, CONST_CS | CONST_PERSISTENT);
    
    REGISTER_LONG_CONSTANT("IA_AC_MODE_AUTO", IA_AC_MODE_AUTO, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("IA_AC_MODE_COOL", IA_AC_MODE_COOL, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("IA_AC_MODE_DEHUMIDIFY", IA_AC_MODE_DEHUMIDIFY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("IA_AC_MODE_WIND", IA_AC_MODE_WIND, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("IA_AC_MODE_HEATING", IA_AC_MODE_HEATING, CONST_CS | CONST_PERSISTENT);
    
    REGISTER_LONG_CONSTANT("IA_AC_POWER_ON", IA_AC_POWER_ON, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("IA_AC_POWER_OFF", IA_AC_POWER_OFF, CONST_CS | CONST_PERSISTENT);
    
    // 不上锁
    REGISTER_LONG_CONSTANT("AC_LOCK_NONE", AC_LOCK_NONE, CONST_CS | CONST_PERSISTENT);
    // 禁止所以遥控器操作
    REGISTER_LONG_CONSTANT("AC_LOCK_ALL", AC_LOCK_ALL, CONST_CS | CONST_PERSISTENT);
    // 禁止除开关机以外的操作
    REGISTER_LONG_CONSTANT("AC_LOCK_EXPECT_ONOFF", AC_LOCK_EXPECT_ONOFF, CONST_CS | CONST_PERSISTENT);
    
    // IA.CODE
    REGISTER_LONG_CONSTANT("UCSOT_IA_CODE", UCSOT_IA_CODE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_PROCESS", UCAT_CODE_PROCESS, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_MATCH", UCAT_CODE_MATCH, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_LIST", UCAT_CODE_LIST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_INFO", UCAT_CODE_INFO, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_DATA", UCAT_CODE_DATA, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_DATA2", UCAT_CODE_DATA2, CONST_CS | CONST_PERSISTENT);

    REGISTER_LONG_CONSTANT("UCAT_CODE_RC_INFO", UCAT_CODE_RC_INFO, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_RC_KEY", UCAT_CODE_RC_KEY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_RC_LEARN", UCAT_CODE_RC_LEARN, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_RC_CTRL", UCAT_CODE_RC_CTRL, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_CODE_RC_MATCH", UCAT_CODE_RC_MATCH, CONST_CS | CONST_PERSISTENT);
	REGISTER_LONG_CONSTANT("UCAT_CODE_RC_MATCH_STATE", UCAT_CODE_RC_MATCH_STATE, CONST_CS | CONST_PERSISTENT);

    REGISTER_LONG_CONSTANT("UCAT_CODE_MAX", UCAT_CODE_MAX, CONST_CS | CONST_PERSISTENT);
    
    
    // IA.PUBLIC.
    REGISTER_LONG_CONSTANT("UCSOT_IA_PUBLIC", UCSOT_IA_PUBLIC, CONST_CS | CONST_PERSISTENT);
    /* IA.PUBLIC.EXCEPTION */
    REGISTER_LONG_CONSTANT("UCAT_IA_PUBLIC_PERIOD_TIMER", UCAT_IA_PUBLIC_PERIOD_TIMER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IA_PUBLIC_EXCEPTION", UCAT_IA_PUBLIC_EXCEPTION, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IA_PUBLIC_WIFI_SET", UCAT_IA_PUBLIC_WIFI_SET, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IA_PUBLIC_EXTENDED_TIMER", UCAT_IA_PUBLIC_EXTENDED_TIMER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IA_PUBLIC_TMP_CURVE", UCAT_IA_PUBLIC_TMP_CURVE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IA_PUBLIC_TMP_CURVE_UTC", UCAT_IA_PUBLIC_TMP_CURVE_UTC, CONST_CS | CONST_PERSISTENT);


    /* IA.TBHEATER */
    REGISTER_LONG_CONSTANT("UCSOT_IA_TBHEATER", UCSOT_IA_TBHEATER, CONST_CS | CONST_PERSISTENT);
    /* IA.TBHEATER.BINDSN_S */
    REGISTER_LONG_CONSTANT("UCAT_TBHEATER_BINDSN_S", UCAT_TBHEATER_BINDSN_S, CONST_CS | CONST_PERSISTENT);
    /* IA.TBHEATER.FAULTREPORT_S */
    REGISTER_LONG_CONSTANT("UCAT_TBHEATER_FAULTREPORT_S", UCAT_TBHEATER_FAULTREPORT_S, CONST_CS | CONST_PERSISTENT);
    /* IA.TBHEATER.DEVINFO_S */
    REGISTER_LONG_CONSTANT("UCAT_TBHEATER_DEVINFO_S", UCAT_TBHEATER_DEVINFO_S, CONST_CS | CONST_PERSISTENT);
    
    
    
    
    /*
    STORAGE(存储)
    */
    // storage.
    REGISTER_LONG_CONSTANT("UCOT_STORAGE", UCOT_STORAGE, CONST_CS | CONST_PERSISTENT);
    
    // storage.string.
    REGISTER_LONG_CONSTANT("UCSOT_STORAGE_STRING", UCSOT_STORAGE_STRING, CONST_CS | CONST_PERSISTENT);
    // storage.binary.
    REGISTER_LONG_CONSTANT("UCSOT_STORAGE_BINARY", UCSOT_STORAGE_BINARY, CONST_CS | CONST_PERSISTENT);
    // storage.packet.
    REGISTER_LONG_CONSTANT("UCSOT_STORAGE_PACKET", UCSOT_STORAGE_PACKET, CONST_CS | CONST_PERSISTENT);
    
    // storage.packet.receive
    REGISTER_LONG_CONSTANT("UCAT_PACKET_RECEIVE", UCAT_PACKET_RECEIVE, CONST_CS | CONST_PERSISTENT);
    // storage.packet.send
    REGISTER_LONG_CONSTANT("UCAT_PACKET_SEND", UCAT_PACKET_SEND, CONST_CS | CONST_PERSISTENT);
    
    
    
    /*
    REGISTER_LONG_CONSTANT("UPGRADE", UPGRADE, CONST_CS | CONST_PERSISTENT);
    */
    REGISTER_LONG_CONSTANT("UCOT_UPGRADE", UCOT_UPGRADE, CONST_CS | CONST_PERSISTENT);
    
    REGISTER_LONG_CONSTANT("UCSOT_UPGRADE_FLASH", UCSOT_UPGRADE_FLASH, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_FLASH_FLASHINFO", UCAT_FLASH_FLASHINFO, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_FLASH_ERASE", UCAT_FLASH_ERASE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_FLASH_UPGRADE", UCAT_FLASH_UPGRADE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_FLASH_COPY", UCAT_FLASH_COPY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_FLASH_ERASE_STM", UCAT_FLASH_ERASE_STM, CONST_CS | CONST_PERSISTENT);

    REGISTER_LONG_CONSTANT("UCOT_DEVPRO", UCOT_DEVPRO, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCSOT_DEVPRO_IR", UCSOT_DEVPRO_IR, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IR_VALKADKB", UCAT_IR_VALKADKB, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IR_CURKB", UCAT_IR_CURKB, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IR_ADJUST", UCAT_IR_ADJUST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCAT_IR_HLW8012", UCAT_IR_HLW8012, CONST_CS | CONST_PERSISTENT);

    // udp control action
    REGISTER_LONG_CONSTANT("UCA_NONE", UCA_NONE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_REQUEST", UCA_REQUEST, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_REPLY", UCA_REPLY, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_QUESTION", UCA_QUESTION, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_ANSWER", UCA_ANSWER, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_RESULT", UCA_RESULT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_REDIRECT", UCA_REDIRECT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_RESET", UCA_RESET, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_GET", UCA_GET, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_SET", UCA_SET, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_DELETE", UCA_DELETE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UCA_PUSH", UCA_PUSH, CONST_CS | CONST_PERSISTENT);

    /*注册UDP CONTROL控制协议*/
    REGISTER_LONG_CONSTANT("CMD_UDP_AUTH",   CMD_UDP_AUTH, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("CMD_UDP_KEEPLIVE",  CMD_UDP_KEEPLIVE, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("CMD_UDP_CTRL",  CMD_UDP_CTRL, CONST_CS | CONST_PERSISTENT);

    /*注册通用类型 用于pack unpack*/
    REGISTER_LONG_CONSTANT("UC_BIT",   UC_BIT, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_INT8",  UC_INT8, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_INT16", UC_INT16, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_INT32", UC_INT32, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_INT64", UC_INT64, CONST_CS | CONST_PERSISTENT);
    
    REGISTER_LONG_CONSTANT("UC_UINT8",  UC_UINT8, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_UINT16", UC_UINT16, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_UINT32", UC_UINT32, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_UINT64", UC_UINT64, CONST_CS | CONST_PERSISTENT);
    REGISTER_LONG_CONSTANT("UC_STRING", UC_STRING, CONST_CS | CONST_PERSISTENT);
    
    REGISTER_LONG_CONSTANT("IS_LITTLE_ENDIAN", IS_LITTLE_ENDIAN, CONST_CS | CONST_PERSISTENT); 
    REGISTER_LONG_CONSTANT("IS_BIG_ENDIAN", IS_BIG_ENDIAN, CONST_CS | CONST_PERSISTENT); 

    return SUCCESS;
}
/* }}} */

/* {{{ PHP_MSHUTDOWN_FUNCTION
 */
PHP_MSHUTDOWN_FUNCTION(wechat)
{
/* uncomment this line if you have INI entries
    UNREGISTER_INI_ENTRIES();
*/
    return SUCCESS;
}
/* }}} */

/* Remove if there's nothing to do at request start */
/* {{{ PHP_RINIT_FUNCTION
 */
PHP_RINIT_FUNCTION(wechat)
{
    return SUCCESS;
}
/* }}} */

/* Remove if there's nothing to do at request end */
/* {{{ PHP_RSHUTDOWN_FUNCTION
 */
PHP_RSHUTDOWN_FUNCTION(wechat)
{
    return SUCCESS;
}
/* }}} */

/* {{{ PHP_MINFO_FUNCTION
 */
PHP_MINFO_FUNCTION(wechat)
{
    php_info_print_table_start();
    php_info_print_table_header(2, "wechat support", "enabled");
    php_info_print_table_end();

/* Remove comments if you have entries in php.ini
     DISPLAY_INI_ENTRIES();
*/
}
/* }}} */


/* Remove the following function when you have successfully modified config.m4
   so that your module can be compiled into PHP, it exists only for testing
   purposes. */

/* Every user-visible function in PHP should document itself in the source */
/* {{{ proto string confirm_wechat_compiled(string arg)
   Return a string to confirm that the module is compiled in */
PHP_FUNCTION(confirm_wechat_compiled)
{
    char *arg = NULL;
    int arg_len, len;
    char *strg;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "s", &arg, &arg_len) == FAILURE) {
        return;
    }

    len = spprintf(&strg, 0, "Congratulations! You have successfully modified ext/%.78s/config.m4. Module %.78s is now compiled into PHP.", "wechat", arg);
    RETURN_STRINGL(strg, len, 0);
}
/* }}} */
/* The previous line is meant for vim and emacs, so it can correctly fold and 
   unfold functions in source code. See the corresponding marks just before 
   function definition, where the functions purpose is also documented. Please 
   follow this convention for the convenience of others editing your code.
*/

PHP_FUNCTION(wechat_udp_version)
{
    if (zend_parse_parameters_none() == FAILURE) {
        return;
    }

    RETURN_STRINGL(PHP_WECHAT_VERSION, strlen(PHP_WECHAT_VERSION), 0);
}

PHP_FUNCTION(wechat_udp_set_global)
{
    long option;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "l", &option) == FAILURE) {
        php_printf("Set option failed by invalid parameter,requiring long\n");
        return;
    }

    uc_set_global(option);
}


PHP_FUNCTION(wechat_udp_bind_pack)
{
    char *arg = NULL;
    long arg_len;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "s", &arg, &arg_len) == FAILURE) {
        php_printf("Udp bind pack failed by invalid parameter,requiring string\n");
        return;
    }

    uc_bind_pack(return_value, arg, arg_len);
}

PHP_FUNCTION(wechat_udp_bind_unpack)
{
    char *arg = NULL;
    long arg_len;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "s", &arg, &arg_len) == FAILURE) {
        php_printf("Udp bind unpack failed by invalid parameter,requiring string\n");
        return;
    }

    uc_bind_unpack(return_value, arg, arg_len);
}

PHP_FUNCTION(wechat_udp_control_pack)
{
    long option = 0;
    zval *cmd = NULL;
    zval *sn  = NULL;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zzl", &sn, &cmd, &option) == FAILURE) {
        php_printf("Udp control pack failed by invalid parameter\n");
        return;
    }

    uc_control_pack(return_value, sn, cmd, option);
}

PHP_FUNCTION(wechat_udp_control_unpack)
{
    char *buff= NULL;
    long  buff_len= 0;
    long option = 0;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "s|l", &buff, &buff_len, &option) == FAILURE) {
        php_printf("Udp control unpack failed by invalid parameter\n");
        return;
    }

    uc_control_unpack(return_value, buff, buff_len, option);
}

PHP_FUNCTION(wechat_udp_hex_unpack)
{
    zval *value = NULL;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &value) == FAILURE) {
        php_printf("Udp control devinfo unpack failed by invalid parameter\n");
        return;
    }
    array_init(return_value);
    uc_control_unpack_unknow(return_value, NULL, Z_STRVAL_P(value), Z_STRLEN_P(value));

}

PHP_FUNCTION(wechat_pack)
{
    zval *value = NULL;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &value) == FAILURE) {
        php_printf("wechat pack failed by invalid parameter\n");
        return;
    }
    
    uc_pack(return_value, value);
}

PHP_FUNCTION(wechat_unpack)
{
    zval *format = NULL;
    zval *input = NULL;
    zval *unpack = NULL;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "zzz", &input, &format,&unpack) == FAILURE) {
        php_printf("wechat unpack failed by invalid parameter\n");
        return;
    }
    
    uc_unpack(return_value, input, format, unpack);
}

PHP_FUNCTION(wechat_udp_control_devinfo_unpack)
{
    char *arg = NULL;
    long arg_len;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "s", &arg, &arg_len) == FAILURE) {
        php_printf("Udp control devinfo unpack failed by invalid parameter\n");
        return;
    }
    uc_control_devinfo_unpack(return_value, arg, arg_len);
}

PHP_FUNCTION(mycrypt_xxtea)
{
    char *msg = NULL;
    long msg_len = 0;
    
    char *key = NULL;
    long key_len = 0;
    u_int8_t is_encrypt = 0;

    if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "ssb", &msg, &msg_len,&key, &key_len,&is_encrypt) == FAILURE) {
        php_printf("mycrypt_xxtea failed by invalid parameter\n");
        return;
    }
    if (key_len != 16 || msg_len%4 != 0 || msg_len == 0) {
        return;
    }

    u_int8_t pack_buff[1024] = {0};

    u_int32_t* v = (u_int32_t*)msg;
    tea_key_t tea;
    memcpy(tea.k, key, key_len);
    memcpy(pack_buff, msg, msg_len);
    if (is_encrypt) {
        developerid_enc(pack_buff, msg_len, &tea);
    } else {
        developerid_dec(pack_buff, msg_len, &tea);
    }
    UC_ZVAL_STRINGL(return_value, pack_buff, msg_len, 1);
}

/*
 * Local variables:
 * tab-width: 4
 * c-basic-offset: 4
 * End:
 * vim600: noet sw=4 ts=4 fdm=marker
 * vim<600: noet sw=4 ts=4
 */
